### ISSUE TITLE
Skin for k9s?

### ISSUE THREAD

**Issue by NeckBeardPrince** [diegoulloao/neofusion.iterm#3]
Not sure where to put this request, but how hard would it be to create a skin for [k9s](https://k9scli.io/topics/skins/)? If you have a way to donate I'd be happy to.

**Comment by diegoulloao** [comment]
> Not sure where to put this request, but how hard would it be to create a skin for [k9s](https://k9scli.io/topics/skins/)? If you have a way to donate I'd be happy to.

Discussions tab for all requests.
I'm planning to port `neofusion` to some others terminals and TUI's.
Could you try this one? (WIP), is a start point...

https://github.com/diegoulloao/neofusion.k9s

I'll appreciate your feedback, also if you can open a discussion and share some screenshots using the skin, I couldn't test it right because I'm facing this issue: https://github.com/derailed/k9s/issues/2428

Hope this can help.

**Comment by NeckBeardPrince** [comment]
> > Not sure where to put this request, but how hard would it be to create a skin for [k9s](https://k9scli.io/topics/skins/)? If you have a way to donate I'd be happy to.
> 
> Discussions tab for all requests.
> 
> I'm planning to port `neofusion` to some other terminals and TUI's. Could you try this one? (WIP), is a start point...
> 
> https://github.com/diegoulloao/neofusion.k9s
> 
> I'll appreciate your feedback, also if you can open a discussion and share some screenshots using the skin, I couldn't test it right because I'm facing this issue: [derailed/k9s#2428](https://github.com/derailed/k9s/issues/2428)
> 
> Hope this can help.

> I'll appreciate your feedback, also if you can open a discussion and share some screenshots using the skin

Sure, do you want to enable [Discussions](https://github.com/diegoulloao/neofusion.k9s)? 

>  I couldn't test it right because I'm facing this issue: [derailed/k9s#2428](https://github.com/derailed/k9s/issues/2428)

Odd, I had the same issue, but it was resolved after he released an update.

**Comment by diegoulloao** [comment]
@NeckBeardPrince that's weird actually I've installed the latest version.
Hey, is enabled now

**Comment by diegoulloao** [comment]
BTW, I've enabled my sponsor profile and a patreon account on all my projects :)

**Comment by NeckBeardPrince** [comment]
> @NeckBeardPrince that's weird actually I've installed the latest version. Hey, is enabled now

Were you able to get k9s working?

**Comment by diegoulloao** [comment]
> > @NeckBeardPrince that's weird actually I've installed the latest version. Hey, is enabled now
> 
> Were you able to get k9s working?

Yes, it worked after install the latest macOs update

Hey thank you for sponsor me ❤️ I really appreciate it, your support helps me continue creating and sharing innovative projects :)

**Comment by diegoulloao** [comment]
@NeckBeardPrince now is stable: https://github.com/diegoulloao/neofusion.k9s
Anything comments just LMK
